version: '2'

services:
  seeddms:
    restart: always
    image: fitz22/docker-seeddms1:latest
    networks:
    - traefik
    ports:
    - "8780:80"
    volumes:
    - /home/florent/docker/seeddms/60:/var/www/seeddms
    labels:
    - "traefik.frontend.rule=Host:flow.domainname.com"
    - "traefik.port=80"
    - "traefik.backend=seeddms"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.docker.network=traefik"
    

networks:
  traefik:
    external:
      name: traefik
